# Generated by Django 5.2.1 on 2025-05-25 13:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matify_api', '0002_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCredits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credits_remaining', models.IntegerField(default=0)),
                ('credits_used', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_credits', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
