# Generated by Django 5.2.1 on 2025-06-26 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matify_api', '0004_generatedimage_processedimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainedmodel',
            name='image_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
